// This file was auto-generated by ML.NET Model Builder. 
// This file is no longer needed. All ModelBuilder logic has been moved to MyML.NetAppML.Lib/ModelBuilder.cs.
// This file is intentionally left empty to avoid confusion and duplicate logic.
// You can safely delete this file from the ConsoleApp project.
