// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.ML;
using Microsoft.ML.Data;
using MyML_NetAppML.Model;

namespace MyML_NetAppML.ConsoleApp
{
}
