// This file was auto-generated by ML.NET Model Builder. 

using System;
using MyML_NetAppML.Model;
using MyML_NetAppML.ConsoleApp.Properties;

namespace MyML_NetAppML.ConsoleApp
{
    sealed class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                SentimentText = @"==RUDE== Dude, you are rude upload that carl picture back, or else.",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine(Resources.UsingModelToMakeSinglePrediction);
            Console.WriteLine($"SentimentText: {sampleData.SentimentText}");
            Console.WriteLine($"\n\nPredicted Sentiment value {predictionResult.Prediction} \nPredicted Sentiment scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine(Resources.EndOfProcessMessage);
            Console.ReadKey();
        }
    }
}
